name: Industrialisation continue sur le serveur Alwaysdata

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connexion SSH et déploiement
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.alwaydata_username }}.alwaysdata.net"
          username: ${{ secrets.alwaydata_username }}
          password: ${{ secrets.alwaydata_password }}
          script: |
            cd $HOME
            rm -rf temp_deploy
            git clone --depth=1 https://github.com/${{ github.repository }}.git temp_deploy

            # Supprime .git, .github, etc.
            rm -rf temp_deploy/.git temp_deploy/.github

            # Synchronise dans www/
            rsync -av --delete temp_deploy/ $HOME/www/

            # Nettoyage temporaire
            rm -rf temp_deploy
